### ISSUE TITLE
Lovelace becomes unstable when module loaded

### ISSUE THREAD

**Issue by lightmaster** [dmulcahey/zha-network-visualization-card#15]
When the module is loaded as a resource in Lovelace, Lovelace becomes unstable and requires a browser refresh to load every page I navigate to within it. For instance, if I press the configuration button in the sidebar, I'll get a loading circle that seems to last indefinitely until I press F5 to reload. Navigate to an other part of Lovelace and I have to press F5 again. I am also unable to press the pencil icon to edit a tab.

If I get into the raw config editor and remove the resource, Lovelace will begin to function correctly as soon as I hit the save button, without a HA restart.

I don't know where any logs are stored at, but I'd be happy to send any if instructed on where they are.

**Comment by chmielowiec** [comment]
Same here. I can't access some resources navigating, only by direct url, like @lightmaster described.
Some webpack error, chrome console (chunk id may change):
```
Error loading page developer-tools ChunkLoadError: Loading chunk 109 failed.
(missing: http://192.168.1.129:8123/frontend_latest/chunk.81da90cd1edea4b59745.js)
    at Function.i.e (http://192.168.1.129:8123/frontend_latest/app.83a8dbf7.js:2:4995)
    at Object.developer-tools [as load] (http://192.168.1.129:8123/frontend_latest/app.83a8dbf7.js:1270:3277)
    at HTMLElement.value (http://192.168.1.129:8123/frontend_latest/app.83a8dbf7.js:942:11731)
    at HTMLElement.performUpdate (http://192.168.1.129:8123/frontend_latest/app.83a8dbf7.js:2:13701)
    at HTMLElement._enqueueUpdate (http://192.168.1.129:8123/frontend_latest/app.83a8dbf7.js:2:13331)
```
It's weird, because in network panel I can see:
```
Request URL: http://192.168.1.129:8123/frontend_latest/chunk.81da90cd1edea4b59745.js
Request Method: GET
Status Code: 200 OK (from disk cache)
```
Incognito mode/disabled caches don't change anything. HA logs nothing about it.

**Comment by dmulcahey** [comment]
I have a few ZHA things that are more pressing at the moment. I'll get to this soon(ish)

**Comment by blair287** [comment]
Yep exact same issues

**Comment by stalakerob** [comment]
I use HA Core 0.107.5 with Raspbian Buster in a virtual python env. I also use HACS (not for this component though - seems to be not supported).  When adding this lovelace component strange things happen. Lovelace becomes unresponsive, other lovelace cards fail after a while and error messages appear instead. The developer tools cannot be used after some time either.  Lovelace UI configuration cannot be used (nothing happens when trying to change something). Refreshing does not help. Seems somethings gets screwed up completely.

**Comment by Sanfam** [comment]
Confirming the same, though no additional information.  The only means to rectify this without restoring from a backup was by removing the custom lovelace module code and orphaning the card itself, returning my ability to edit the UI in any way.

**Comment by blair287** [comment]
Really want this feature in HA shame about this issues any chance of it being fixed?

**Comment by dmulcahey** [comment]
I’ll spend some time on this towards the end of the week. Been working on more pressing things for a while

**Comment by blair287** [comment]
Thanks think its the only thing missing to bring ZHA up to Zigbee2mqtt or deconz

**Comment by jonwaland** [comment]
just adding seeing similar unstableness in 0.109.6, in Python venv


```
arch | x86_64
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
os_version | 4.4.0-173-generic
python_version | 3.8.2
timezone | Australia/Sydney
version | 0.109.6
virtualenv | true

```

**Comment by Martinvdm** [comment]
I do have the same issue. Ha hangs a lot a giving loading circle when this Card loaded, but I couldn’t track down if it is this card or ZHA-map addition which is causing the issue.

**Comment by nthewara** [comment]
+1 - I have similar issues with lovelace UI randomly not rendering after adding ZHA Map card. I have disabled it at the moment.

**Comment by blair287** [comment]
Any chance this can be fixed would be a good feature to have deconz and zigbee2mqtt both have this feature.

**Comment by TheJulianJES** [comment]
As a "workaround", I just created a new dashboard with the ZHA network card and for the second tab this network visualization card. When navigating somewhere else, one simple reload fixes Lovelace.

**Comment by dmulcahey** [comment]
should be fixed
