### ISSUE TITLE
Error: Custom element not found: zha-network-visualization-card

### ISSUE THREAD

**Issue by onlinegill** [dmulcahey/zha-network-visualization-card#30]
No matter what i do i cant make it work it shows following error when i try to add custom card 

Custom element doesn't exist: zha-network-visualization-card.
type: 'custom:zha-network-visualization-card'

my resource files is :
url: /local/zha-network-visualization-card.js

**Comment by sacha01** [comment]
hello, same problem

**Comment by PDekker** [comment]
I've found the solution. There is an error in the readme.

The correct link to your resource file should be
/local/zha-network-visualization-card/zha-network-visualization-card.js
