### ISSUE TITLE
"Error: Custom element not found: zha-network-visualization0card

### ISSUE THREAD

**Issue by mrneutron42** [dmulcahey/zha-network-visualization-card#38]
I'm getting this error when trying to create a card for zha-network-visualization.
![error zha-network-visualization-card](https://user-images.githubusercontent.com/70338169/96355527-223e7200-10a8-11eb-9c6d-2a4eeef945e7.PNG)
I followed the directions in the wiki as closely as I could.  
I note that the terminology in the directions doesn't match the menu choices in Home Assistant.   
I'm betting the UI has changed since the directions were written?
For example, the is no "Configure UI" choice in the ⋮ circle, only "Edit Dashboard".
![Edit Dashboard](https://user-images.githubusercontent.com/70338169/96370469-8baf9680-1123-11eb-9558-3e9e80406768.PNG)
After that, there are 2 + buttons to choose from:  
1. the upper + button is Add View
![Lovelace + button Add view](https://user-images.githubusercontent.com/70338169/96370487-99fdb280-1123-11eb-93f9-47ebb40f701e.PNG)

2. the lower + button is Add Card
![Lovelace + button Add Card](https://user-images.githubusercontent.com/70338169/96370495-9f5afd00-1123-11eb-8a87-0312b5927ed4.PNG)

Which + button do we choose in the current (2020) versions of Home Assistant?

I'm running HA in a VMWare Virtual Machine:
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.14
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.69
python_version | 3.8.5
supervisor | 247
timezone | America/Chicago
version | 0.116.4
virtualenv | false

**Comment by doudz** [comment]
maybe you didn't put the file zha-network-visualization-card.js in the right folder ?
in your config folder under www/zha-network-visualization-card/zha-network-visualization-card.js

**Comment by mrneutron42** [comment]
It's in there.
```
~ $ cd /config/www/zha-network-visualization-card/
zha-network-visualization-card $ ls
README.md                          zha-network-visualization-card.js
zha-network-visualization-card $
```

The directions in the wiki appear to be for a much older version - out of date.
Step 6 in the wiki cannot be completed, because the listed controls do not exist, in the current version of Home Assistant.
See what I mean?

**Comment by gregoryjstarr** [comment]
In `Configuration` -> `Lovelace Dashboards` -> `Resources` remove the `URL:` and just leave the resource as `/local/zha-network-visualization-card/zha-network-visualization-card.js`

**Comment by mrneutron42** [comment]
Thank you!  Removing the URL: fixed the problem.  I'm seeing a Zigbee map now!

Now we know, the wiki Installation Instructions need to get fixed.

I just made changes to the README.md file and created a Pull Request.
