### ISSUE TITLE
Bug with "box" and "unknow device" instead of "Coordinator"

### ISSUE THREAD

**Issue by jonathan-gtd** [dmulcahey/zha-network-visualization-card#41]
Hi,

There is a bug with PiZiGate, it says device type "unknow" and its a circle
![image](https://user-images.githubusercontent.com/2879180/99862706-05abc300-2b9b-11eb-9775-6d40ceb66fbd.png)

I think it's because it's the "else":
![image](https://user-images.githubusercontent.com/2879180/99862739-1f4d0a80-2b9b-11eb-9cab-faca107aa8ae.png)

So, temporarly i changed to:
![image](https://user-images.githubusercontent.com/2879180/99862897-e7929280-2b9b-11eb-963f-754cf7eade20.png)

But it's not a solution, just a bypass

**Comment by MattWestb** [comment]
I think the bug is in in Zigbpy or in zigpy-zigate. The TI CC-253X was having the same problem before but it fixed now.

**Comment by jonathan-gtd** [comment]
Ok thanks ! I close !
