### ISSUE TITLE
zha-network-visualization-card in HA 2020.12 NWK

### ISSUE THREAD

**Issue by MattWestb** [dmulcahey/zha-network-visualization-card#49]
I don't knowing if you like have issues her or in HA github.

As of HA 2020.12.0 is the NMK is start being shown in decimal form (0 for the coordinator) instead of the normal hex (0x0000 for the coordinator).
![ZHA-MAP01](https://user-images.githubusercontent.com/49618193/102343400-cb1b2780-3f9a-11eb-9f4e-73b3c8a8dc10.PNG)

Its more or less one cosmetic thing but its easier finding one device with hex address then its used all over in ZHA.

And as usual great work done !!

**Comment by dmulcahey** [comment]
Already in a PR with some new features here: https://github.com/home-assistant/frontend/pull/7913

please don’t post issues here as the code base is completely different and this code has been deprecated.
